Final changes
Iandmee/NADNES pull request #11
Opened 2022-06-03 22:28 UTC by das747

2022-06-03 23:59 UTC, Iandmee requested changes

2022-06-03 23:59 UTC, Iandmee commented on include/nes_devices/cartridge.h
> +    bool use_CHR_ROM_as_RAM = false;
дефолтную инициализацию делаем через скобки

2022-06-03 23:59 UTC, Iandmee commented on include/nes_devices/dma.h
>      bool activated = false;
дефолтная инициализация через {}

2022-06-03 23:59 UTC, Iandmee commented on include/nes_devices/ppu.h
>          uint8_t OAM_addr_reg = 0;
дефолтная инициализация через {}

2022-06-03 23:59 UTC, Iandmee commented on include/remote_emulator.h
> +    int last_port = -1;
дефолтная инициализация через {}

2022-06-03 23:59 UTC, Iandmee commented on include/nes_devices/R6502.h
>      bool dma_is_active = false;
дефолтная инициализация через {}

2022-06-03 23:59 UTC, Iandmee commented on include/remote_player.h
> +    size_t id;
либо сделать int, либо в функцию add_pseudoname передавать index как size_t

2022-06-03 23:59 UTC, Iandmee commented on include/Server.h
> +    QLabel *statusLabel;
переменные должны быть в одном стиле, в нашем случае snackcase

2022-06-03 23:59 UTC, Iandmee commented on include/colors_map.h
> +extern const std::map<NES::Color, uint8_t> bytes;
bytes лучше заменить на более подходящее имя для глобальной переменной

2022-06-03 23:59 UTC, Iandmee commented on include/config_reader.h
> +const char *const CONFIG_FILE = "../nadnes.conf";
лучше просто const string, а при надобности юзать c_str()

2022-06-03 23:59 UTC, Iandmee commented on src/environment/cheating/apply_cheat.cpp
> +//    apply_cheat->unselectAll = this->findChild<QPushButton *>("unselectAll");
думаю эти комменты тоже надо удалить

2022-06-03 23:59 UTC, Iandmee commented on src/environment/cheating/search_cheat.cpp
> +    if (!checkRam->isChecked() && !checkRom->isChecked()) {
мы стараемся писать переменные в snackcase

2022-06-03 23:59 UTC, Iandmee commented on src/environment/cheating/search_cheat.cpp
> +    //                                     QLineEdit::Normal,
этот закомментированный код тоже надо бы удалить

2022-06-03 23:59 UTC, Iandmee commented on src/environment/cheating/search_cheat.cpp
> +    //    qDebug() << "cheat_num: " << cheat_num;
много комментов

2022-06-03 23:59 UTC, Iandmee commented on src/environment/cheating/search_cheat.cpp
> +    ParamsOfChange paramsOfChange;
snackcase!

2022-06-03 23:59 UTC, Iandmee commented on src/environment/connection_window.cpp
> +//    m_address_edit->clear();
комменты надо бы делитнуть

2022-06-03 23:59 UTC, Iandmee commented on src/environment/player_select_window.cpp
> +    for (int player = 1; player <= 2; ++player) {
мейби в функцию?

2022-06-03 23:59 UTC, Iandmee commented on include/local_emulator.h
> +    void quicksave();
quick_load и quick_save? Чисто на глаз

2022-06-03 23:59 UTC, Iandmee commented on src/nes_devices/cartridge.cpp
> +enum class MapperTypes : uint8_t { NROM = 0, UNROM = 2 };
почему именно 0 и 2?

2022-06-03 23:59 UTC, Iandmee commented on src/remote_player.cpp
> +void RemotePlayer::set_pixel(int row, int column, NES::Color color) {
Вообще во всём проекте очень много int, в местах, где можно указать тип точнее во избежание конфликтов, желательно пробежаться по классам и функциям с интами и проверить, правда ли они там нужны и насколько мы уверены, что не будет неправильных кастов переполнений и проч. Аналогично с qt мапами и прочим.

2022-06-04 10:58 UTC, das747 reviewed
-Автоформатировать нужно в самом конце иначе все комменты съедут.
-Нужно пересмотреть файловую структуру. 
-Вынести значения по умолчанию для парметров конфига.

2022-06-04 10:58 UTC, das747 commented on src/environment/cheating/search_cheat.cpp
> +    QFile defaultSaveFile("../UI/cheating/save_cheat_window.ui");
возможно их стоит запихать в конфиг

2022-06-04 10:58 UTC, das747 commented on src/environment/cheating/search_cheat.cpp
> +    //                                     QLineEdit::Normal,
этот закоментированный код может заменить целый класс

2022-06-04 10:58 UTC, das747 commented on src/environment/cheating/search_cheat.cpp
> +    const int rows = 500;
constexpr, вынести выше а ещё лучше в конфиг

2022-06-04 10:58 UTC, das747 commented on src/environment/connection_window.cpp
> +    loader.load(&file, this);
закрыть файл

2022-06-04 10:58 UTC, das747 commented on src/environment/keymap_window.cpp
> +    QFile file("../UI/keymap.ui");
в конфиг

2022-06-04 10:58 UTC, das747 commented on src/environment/keymap_window.cpp
> +    loader.load(&file, this);
закрыть файл

2022-06-04 10:58 UTC, das747 commented on src/environment/main_window.cpp
>  void MainWindow::refresh_screen() {
можно добавить частоту отрисовки

2022-06-04 10:58 UTC, das747 commented on src/environment/main_window.cpp
> +    QSize qSize(NES::SCREEN_WIDTH * 5, NES::SCREEN_HEIGHT * 5);
это тоже можно нормальными константами сделать

2022-06-04 10:58 UTC, das747 commented on src/environment/main_window.cpp
> +void MainWindow::create_menus() {
наверно можно было бы автоматизировать...

2022-06-04 10:58 UTC, das747 commented on src/environment/main_window.cpp
> +    m_image_label->update();
можно заменить на refresh_screen

2022-06-04 10:58 UTC, das747 commented on src/environment/player_select_window.cpp
> +    loader.load(&file, this);
закрыть файл

2022-06-04 10:58 UTC, das747 commented on src/environment/player_select_window.cpp
> +    QFile file("../UI/player_select.ui");
в конфиг

2022-06-04 10:58 UTC, das747 commented on src/environment/player_select_window.cpp
> +    close();
hide

2022-06-04 10:58 UTC, das747 commented on include/mappers/UNROM.h
> +    uint8_t CHR_ROM_size;
не используются

2022-06-04 10:58 UTC, das747 commented on src/nes_devices/cartridge.cpp
> +enum class MapperTypes : uint8_t { NROM = 0, UNROM = 2 };
потому что это их номера в формате iNes, они прописаны в хедерах

2022-06-04 10:58 UTC, das747 commented on src/nes_devices/dma.cpp
> +    file.write(reinterpret_cast<char *>(this), sizeof(Dma) - 8);
\- sizeof bus

2022-06-04 10:58 UTC, das747 commented on include/search.h
> +struct Place {
Storage?

2022-06-04 10:58 UTC, das747 commented on include/cheat_db_handler2.h
> +class CheatDbHandler {
нужно удалить лишний файл или переименовать классы

2022-06-04 10:58 UTC, das747 commented on include/colors_map.h
> +extern const std::map<NES::Color, uint8_t> bytes;
colors_from_bytes
bytes_from_colors

2022-06-04 10:58 UTC, das747 commented on include/config_reader.h
> +namespace {
лучше _Congif и вынести в cpp, потому что сейчас при каждом инклуде разные функции получаются

2022-06-04 10:58 UTC, das747 commented on include/gamepad.h
> +
возможно здесь переводы строк стоит убрать

2022-06-04 10:58 UTC, das747 commented on src/main_controller.cpp
> +    connect(m_main_window.m_open_pl2_keymap_act,
стиль ужасный, но я не знаю как это исправить

2022-06-04 10:58 UTC, das747 commented on src/main_controller.cpp
> +    }
много раз повторяется, возможно стоит сделать что то вроде free_qptr

2022-06-04 10:58 UTC, das747 commented on include/search.h
> +};
первеоды строк между структурами и методами

2022-06-04 10:58 UTC, das747 commented on include/remote_player.h
> +                          config::get_value("server.send_framerate", 20);
вынести дефолтные настройки куда нибудь

2022-06-04 10:58 UTC, das747 commented on src/remote_player.cpp
> +//socket->write(image);
удалить

2022-06-05 08:38 UTC, merged